FROM debian:stretch-slim
RUN apt-get -y update && \
    apt-get -y install make \
                       cmake \
                       g++-6 \
                       clang++-3.9 && \
    apt-get -y clean
