FROM debian:jessie-slim
RUN apt-get -y update && \
    apt-get -y install make \
                       cmake \
                       g++-4.8 \
                       g++-4.9 \
                       clang++-3.5 && \
    apt-get -y clean
